### ISSUE TITLE
Clicking the `button` again should close the timepicker.

### ISSUE THREAD

**Issue by domharrington** [bengourley/anytime#11]

**Comment by bengourley** [comment]
I'm not sure I agree with this. @jackbrewer what do you think?

**Comment by jackbrewer** [comment]
Hard to say as I haven't really 'used' it let as a CMS user, just testing as a dev.

I can see how it can cause minor annoyances as it is now though:
* Click an input in a form, date picker appears
* Click a day in the datepicker, original form's input gets filled in
* Click next input in the original form, previous input's datepicker stays open, obscuring your view.

This is maybe another issue, in that focussing a different input could close all other datepickers, or even clicking anywhere outside the datepicker. Not really what Dom is asking for though. I can see the advantage of leaving it open when you are clicking dates, so you can change your mind, or correct a mis-placed click.

**Comment by bengourley** [comment]
If it closes upon clicking a date, you never get a chance to select a time.

**Comment by jackbrewer** [comment]
Yeah, I think I said that in an odd way. It's fine to leave open for as long as we can so you can do the time / change your mind and choose different dates etc, but maybe we could try to detect when the User is finished - signified by a click outside the datepicker, or maybe by them focussing a different input (outside the datepicker).

**Comment by domharrington** [comment]
I feel like when clicking a button to perform an action, clicking the same button again should reverse the action. This stood out to me more in the date preview view where there is a button labelled "pick a date" to open.

I think Jack and I are discussing 3 different use cases for closing:
- clicking the `button` twice
- clicking into the datepicker then clicking away
- opening a datepicker when another one is already visible

**Comment by bengourley** [comment]
Ok, so I:

1. Clicking the button twice **should happen in anytime**
2. Clicking into the datepicker then clicking away  **should happen in anytime**
3. Opening a datepicker when another one is already visible **anytime already has this feature. Each instance will close any other open instances when being opened itself**

I think we should add 1. as an option which defaults to off. 2. should be normal behaviour.

**Comment by jackbrewer** [comment]
:+1: Sorry for adding confusion, In my head, anytime is still only attached to inputs.

**Comment by bengourley** [comment]
All of these actions now happen as default behaviour.
