### ISSUE TITLE
You should be able to programmatically update the internal date value

### ISSUE THREAD

**Issue by serby** [bengourley/anytime#16]
Currently if you want to programmatically update the date value you are forced to destroy the picker and recreate it. It would be nice if setting the date value updated the internal model and updated all views.

**Comment by bengourley** [comment]
You can update it by mutating `picker.value` which is a moment instance (you might have to `picker.emit('change', picker.value)` too).

I am open to a `picker.update()` method that wraps this functionality up.

**Comment by serby** [comment]
The important thing is that the views (input and picker) are updated if the internal value changes. Not an easy task. Might require an API change to make `picker.value()` so it is readonly and then there is another function to set/update ie. `picker.set(new Date())` or ``picker.update(new Date())` if you prefer.

**Comment by serby** [comment]
I won't proceed with this without further discussion.

**Comment by bengourley** [comment]
As far as Im aware, all of the updating is done inside the `.on('update')` handler:

**Comment by bengourley** [comment]
As far as I'm aware all of the updating is done inside the `.on('change')` handler so all of that is handled by emitting the event:
https://github.com/bengourley/anytime/blob/master/anytime.js#L56-L62
