### ISSUE TITLE
Month names should be based on locale. 

### ISSUE THREAD

**Issue by serby** [bengourley/anytime#17]
As moment has all the locale information for months, this should be used rather than storing the months in an internal array.

https://github.com/moment/moment/blob/develop/locale/en-gb.js#L14
https://github.com/moment/moment/blob/develop/locale/fr.js#L14

**Comment by bengourley** [comment]
:+1:

**Comment by bengourley** [comment]
Fixed in 27590f861bf43da3f664d1b380ef9a31a1da0729
