### ISSUE TITLE
It would be nice if the picker highlighted the date for the currently set date

### ISSUE THREAD

**Issue by serby** [bengourley/anytime#19]

**Comment by bengourley** [comment]
@domharrington has done this in #13. It was release in v0.4.0 Please confirm and close?

**Comment by serby** [comment]
I was looking in the demo.html for v0.4.0 and I can't see it happening. I'll look into it.

**Comment by bengourley** [comment]
It says he added classes, so maybe he didn't add anything to the CSS in the demo.

**Comment by serby** [comment]
I was looking for the class `.anytime-picker__date--selected` but no joy :(

**Comment by bengourley** [comment]
`'anytime-picker__date--current'`

https://github.com/bengourley/anytime/commit/c93891743de36baf4672573c1f0db2c3c391e807#diff-ae60ee2d4811b10e4f945ccb6df0d8c0R212

**Comment by serby** [comment]
I can't see any classes being added.

**Comment by bengourley** [comment]
I have just run demo on master and I see this class on 20th May `anytime-picker__date--current`

**Comment by serby** [comment]
I'm not seeing that either which is weird. But my request was for the selected date to also be highlighted.

**Comment by bengourley** [comment]
Oh, the selected data has always had class on it `anytime-picker__date--selected` (it isn't styled in the demo)

**Comment by serby** [comment]
In the version in 0.4.0 bundle.js is not the same as anytime.js.

**Comment by bengourley** [comment]
bundle.js isn't in git. How are you running the demo? `npm run demo` builds a new bundle.

**Comment by serby** [comment]
When you npm install anytime bundle.js is in the node_modules/anytime folder. If I `npm run demo` I get `bundle.js:1 Uncaught Error: Cannot find module './anytime'` in the browser.

**Comment by serby** [comment]
Even if I do `npm run demo` in my checked out version I get the same error.

**Comment by bengourley** [comment]
Ok I've added `bundle.js` to `.npmignore`. That shouldn't have been there but the custom `.npmignore` meant that the stuff in `.gitignore` wasn't ignored.
