### ISSUE TITLE
Allow customisation of button text

### ISSUE THREAD

**Issue by bengourley** [bengourley/anytime#26]
'Done' and 'Clear' text should be configurable via options.

**Comment by klaemo** [comment]
I can provide a PR. What do you want the options to be called?
`doneText` and `clearText`?

**Comment by bengourley** [comment]
Sounds good to me! Can you make sure to add a test for this behaviour? Thanks.

**Comment by klaemo** [comment]
Will do. :)

**Comment by bengourley** [comment]
Fixed in #27.
