### ISSUE TITLE
Add bundled dist files

### ISSUE THREAD

**Issue by arkon** [bengourley/anytime#42]
Add an easily consumable `anytime.js` and `anytime.min.js` file for "normal" use via a `<script>` tag, for those who aren't using a module system.

**Comment by bengourley** [comment]
:+1: we can get browserify to do this for us if I remember correctly. Would need to decide whether to bundle in moment or require the user to provide it.

**Comment by arkon** [comment]
We could potentially structure it in such a way that they could provide either moment or moment-timezone, although I haven't really looked into that part of the code yet.

**Comment by arkon** [comment]
Also, we could try using [Rollup](https://github.com/rollup/rollup)! I'll give it a spin later -- and also restructure the project a bit so that there's a `src` folder (with the source files) and a `dist` folder (with the bundled files).

**Comment by bengourley** [comment]
Yeah. It's important to make sure we ignore the dist files in the npm ignore so we don't add baggage for browserify consumers.

**Comment by arkon** [comment]
Done via PR #49
