### ISSUE TITLE
Allow including Moment externally for bundled scripts.

### ISSUE THREAD

**Issue by arkon** [bengourley/anytime#50]
Which would allow for choosing either Moment or Moment with timezones. Would also cut down on file size.

**Comment by arkon** [comment]
I'm not actually sure if Browserify supports this... we might have to use Webpack instead.

**Comment by frederikschubert** [comment]
+1 This would be great as for now moment is included twice when using this widget.

**Comment by arkon** [comment]
Done via PR #68.
