### ISSUE TITLE
Safari: Selected date class not set in calendar view

### ISSUE THREAD

**Issue by jackbrewer** [bengourley/anytime#58]
When choosing a day, Safari does not set the expected `anytime-picker__date--selected` class on items when clicked.

Chrome (working as expected):
![anytime-58-chrome](https://cloud.githubusercontent.com/assets/720908/11061777/4c3ac378-87a1-11e5-81a8-51f1b8f6f1f1.gif)

Safari (not working as expected):
![anytime-58-safari](https://cloud.githubusercontent.com/assets/720908/11061779/4e816e0c-87a1-11e5-996b-6c21ca971b32.gif)

---

Additionally, when a date has previously been chosen and anytime is re-opened, the pre-chosen date is not selected. In the following Safari screenshot, the `12` should be selected when anytime is opened. This works as expected in other browsers

![anytime-58-open](https://cloud.githubusercontent.com/assets/720908/11061853/dae76f2c-87a1-11e5-8b50-a74bf5f76c7f.gif)

**Comment by jackbrewer** [comment]
This seems fixed as of 1.3.0 - either the changes fixed it or I my implementation of 1.2 was odd. Either way, good now.

**Comment by arkon** [comment]
It was possibly fixed after [removing the classList library](https://github.com/bengourley/anytime/commit/82ada93ec16e852674abeee7ab09bf339e5812a5).

**Comment by jackbrewer** [comment]
Looks probable, thanks!
